### PR TITLE
Extending provenance report history

### PR DESCRIPTION
**Pull request by antony-wilson**
The api/prov endpoint now accepts the parameter `depth`

#152

### CODE REVIEW

**Comment by nathan-cummings-ukaea** [comment]
First thing I noticed:

Using Sonias db, I'm looking at the prov reports for data products 2 and 3. This isn't related to the `depth` flag, but both of those reports include the other data product as an entity even though they don't appear to be a part of each other's provenance tree - they just happen to have come from the same code run.

**Comment by nathan-cummings-ukaea** [comment]
I'm trying to understand what is going on here, the list `input_files` doesn't seem to contain what I expect it to.

**Comment by antony-wilson** [comment]
> I'm trying to understand what is going on here, the list `input_files` doesn't seem to contain what I expect it to.

Could be where I'm going wrong

**Comment by nathan-cummings-ukaea** [comment]
> > I'm trying to understand what is going on here, the list `input_files` doesn't seem to contain what I expect it to.
> 
> Could be where I'm going wrong

Happy to look at it over zoom if you want.

**Comment by nathan-cummings-ukaea** [comment]
I think I have a fix...

**Comment by antony-wilson** [comment]
Sorry been in and out of meeting this afternoon, do you just want to go for it with the fix

**Comment by nathan-cummings-ukaea** [comment]
Hopefully this works for you. Please let me know if I need to look at it again.

**Pull request merged**
