### PR TITLE
Automatically create object component representing the whole object

### PR DESCRIPTION
**Pull request by alahiff**
Solves https://github.com/FAIRDataPipeline/data-registry/issues/45

### CODE REVIEW

**Review by richardreeve — APPROVED** [review]

**Comment by richardreeve** [comment]
This looks simple enough, hopefully. I presume that although the `whole_object` field is generated on the fly, it's still possible to search for it? i.e. ask for the component which has the flag set to True?

**Comment by richardreeve** [comment]
Assuming that is fine, @alahiff do you want to merge this and we'll just have one more thing before we release 1.0-rc1?

**Comment by alahiff** [comment]
Good question :-) We don't seem to have any search functionality currently, but I tried doing something like this:
```
models.ObjectComponent.objects.filter(Q(whole_object=True))
```
and this didn't work - it said `whole_object` isn't a field. I've corrected this by changing it back to a standard DB field with a default value of `False`.

https://github.com/FAIRDataPipeline/data-registry/pull/83/commits/35bc1e3b8b19b8ca8415044f38cd898d59d6ef16

Now queries work correctly.

**Comment by alahiff** [comment]
@richardreeve I'm now happy for this to be merged.

**Pull request merged**
