### PR TITLE
Json ld

### PR DESCRIPTION
**Pull request by antony-wilson**
This branch adds functionality to get the provenance report in a `JSON-LD` format.
As part of this namespaces were added to the report:
```
  prefix lreg <http://localhost:8000/>
  prefix reg <https://data.scrc.uk/>
  prefix fair <https://data.scrc.uk/vocab/#>
  prefix dcat <http://www.w3.org/ns/dcat#>
  prefix dcmitype <http://purl.org/dc/dcmitype/>
  prefix dcterms <http://purl.org/dc/terms/>
  prefix foaf <http://xmlns.com/foaf/spec/#>
```
**N.B.** Either the `lreg` or `reg` namespace will be used depending on if the register is local.
The `fair` namespace is used for terms not in the other vocabs.

In order to determine is this is a local registry and to provide a central namespace for vocal terms the variable `CENTRAL_REGISTRY_URL` was added to the settings files.

~~An additional requirement of rdflib-jsonld has been added.~~
The version of rdflib has been increased to 6.0.1, this include what was the rdflib-jsonld package.

In the views module there is a new renderer for JSON-LD also the comments have been restructured to improve their display on the API page.

### CODE REVIEW

**Comment by nathan-cummings-ukaea** [comment]
I get a 500 error when I try to navigate to (for example) http://localhost:8000/api/prov-report/1/?format=json-ld

I'll have a look at the debug output after lunch in case I'm doing something wrong.

**Comment by antony-wilson** [comment]
> I get a 500 error when I try to navigate to (for example) http://localhost:8000/api/prov-report/1/?format=json-ld
> 
> I'll have a look at the debug output after lunch in case I'm doing something wrong.

Did you install rdflib-jsonld?

**Comment by nathan-cummings-ukaea** [comment]
Ah, no. Do you know how to install it for Mac? I've had a quick google and there's no Homebrew version that I can see.

**Comment by antony-wilson** [comment]
you should be able to pip install it

**Comment by nathan-cummings-ukaea** [comment]
Ah ok, found the issue. It's not to pip install rdflib-jsonld. This has been deprecated and we should use the rdflib package, which we already do, but update it to version 6.0.1. I'll make this change and push it.

**Comment by nathan-cummings-ukaea** [comment]
Ok, cool. Not an exhaustive test but I installed fresh from this branch directly, used the add_example_data function and then was able to generate json_ld reports for the couple of data products that I checked. Thanks @antony-wilson !

**Review by nathan-cummings-ukaea — APPROVED** [review]

**Comment by nathan-cummings-ukaea** [comment]
Should we also update the requirements.txt for the remote registry, just for consistency? Possibly a question for @alahiff ?

**Pull request merged**
