### PR TITLE
Add a citation file

### PR DESCRIPTION
**Pull request by antony-wilson**
#112

The list of authors was obtain from the list of people that have committed to the repo

### CODE REVIEW

**Comment by richardreeve** [comment]
Great! It's frustrating that you have to put a version number into the `CITATION.cff` file, otherwise it would be a no brainer to adopt these, but I guess we just need to remember to update the version here at the same time as tagging and version numbers elsewhere.

**Comment by agbeltran** [comment]
the version is for the CFF format, not about our repo

**Comment by agbeltran** [comment]
ah, sorry, yes, there is also the registry version!

**Comment by antony-wilson** [comment]
@richardreeve I pulled in the list of authors from the list of committers at  https://github.com/FAIRDataPipeline/data-registry/graphs/contributors but I have just spotted that you are not there but you are listed as a contributor on the front page. Do you want me to add you to the list of authors?

**Comment by antony-wilson** [comment]
The "version" is an optional field but I thought it would be useful

**Comment by richardreeve** [comment]
> The "version" is an optional field but I thought it would be useful

Well, maybe I've got this wrong, but the problem we found is that `.zenodo.json` files result in Zenodo pulling the version from the tag, but `CITATION.cff` files (I believe) just don't offer a version in the citation if you don't put it in manually, and Zenodo didn't seem to pick it up correctly without a version when I tried earlier. I could have messed up somewhere else though!

**Comment by richardreeve** [comment]
> @richardreeve I pulled in the list of authors from the list of committers at https://github.com/FAIRDataPipeline/data-registry/graphs/contributors but I have just spotted that you are not there but you are listed as a contributor on the front page. Do you want me to add you to the list of authors?

I'm not sure what's going on there with the discrepancy - maybe my contributions were `suggestion`s in PRs that were formally committed by someone else? My feeling is that we should be inclusive on author lists, but I don't feel strongly about it!

**Pull request merged**
