### PR TITLE
Remove Port Restrictions

### PR DESCRIPTION
**Pull request by RyanJField**
Container systems such as docker require ports to be bound to specific / all interfaces i.e. 0.0.0.0:8000. To Resolve this I have added an address flag -a to the start scripts.

### CODE REVIEW

**Comment by RyanJField** [comment]
I have also added a windows runner to the CI, currently testing on python 3.9 but this can be changed when #186 has been merged. Feel free to squash these commits.

**Comment by bobturneruk** [comment]
Win 10, Python 3.9.12

I was able to install using:

```
.\localregistry.bat -d C:\Users\bobturner\fair_registry -b hotfix/port-fix
```

I can start with:

```
start_fair_registry_windows.bat -p 8080 -a 127.0.0.1 -b
```

and see the server running in the browser, so a custom port is OK. 

```
.\stop_fair_registry_windows.bat
```

works.

However this:

```
start_fair_registry_windows.bat -p 8081 -a 192.168.0.15 -b
```

didn't start a server. Returns:

```
curl, Features: AsynchDNS HSTS IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI Unicode UnixSockets alt-svc libz is installed, continuing...
Reading Parameter -p...
Reading Parameter -a...
Reading Parameter -b...
Spawning Server at 192.168.0.15:8081
Writing Session and Port Info
waiting for server to start
```

So it's reading the IP and port correctly. I'm guessing this is actually fine as there's no server on `192.168.0.15` for it to run on - I don't know how django does it's business with this - I guess the `-a` flag is either for Docker somehow or if you want to deploy on an arbitrary server (that exists).

So looking good, I think. Before I leave a review - why do we have `.bat` and .`ps1` files, please? I can't see where the `.ps1` files are being used...

**Comment by RyanJField** [comment]
> Win 10, Python 3.9.12
> 
> I was able to install using:
> 
> ```
> .\localregistry.bat -d C:\Users\bobturner\fair_registry -b hotfix/port-fix
> ```
> 
> I can start with:
> 
> ```
> start_fair_registry_windows.bat -p 8080 -a 127.0.0.1 -b
> ```
> 
> and see the server running in the browser, so a custom port is OK.
> 
> ```
> .\stop_fair_registry_windows.bat
> ```
> 
> works.
> 
> However this:
> 
> ```
> start_fair_registry_windows.bat -p 8081 -a 192.168.0.15 -b
> ```
> 
> didn't start a server. Returns:
> 
> ```
> curl, Features: AsynchDNS HSTS IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI Unicode UnixSockets alt-svc libz is installed, continuing...
> Reading Parameter -p...
> Reading Parameter -a...
> Reading Parameter -b...
> Spawning Server at 192.168.0.15:8081
> Writing Session and Port Info
> waiting for server to start
> ```
> 
> So it's reading the IP and port correctly. I'm guessing this is actually fine as there's no server on `192.168.0.15` for it to run on - I don't know how django does it's business with this - I guess the `-a` flag is either for Docker somehow or if you want to deploy on an arbitrary server (that exists).
> 
> So looking good, I think. Before I leave a review - why do we have `.bat` and .`ps1` files, please? I can't see where the `.ps1` files are being used...

The ps1 files offer an alternative to the batch scripts on windows. On the off chance you can't run batch scripts (remote servers which only offer powershell...). The default behaviour should be the batch scripts but the powershell scripts offer more compatability.

As for the server not running on a specific address this is likely a firewall issue.

**Review by bobturneruk — APPROVED** [review]
I don't have all the expertise or detailed knowledge of this software I'd like to be reviewing this. However, I can figure out how to install and run it, so on that level it's good!

The CI contains "smoke tests" to ensure that the software installs and runs on several platforms without error. I'd suggest maybe expanding these to include the optional PowerShell scripts and to use an IP address other than 127.0.0.1 / localhost.

**Pull request merged**
