### PR TITLE
Allow user to specify alternative port and install directory for registry launch

### PR DESCRIPTION
**Pull request by kzscisoft**
Adds additional bash variable `$PORT` to registry start script, checks value is integer then launches django with it writing this value to a file so the CLI can access it.

### CODE REVIEW

**Comment by kzscisoft** [comment]
Had to move things around a bit, there should be some help strings to hopefully simplify things a bit though.

NOTE: to get this to work in the CI I have not used the traditional install method!

```bash
/bin/bash -c "$(curl -fsSL l<URL>/localregistry.sh)"
```
has now become:
```bash
curl -fsSL <URL>/localregistry.sh | bash -s -- -d $INSTALL_DIR -b BRANCH}
```

Also @alahiff I had to swap out the way you were selecting the branch to use in the CURL as my branch has slashes in it so it was breaking, I think the new method should work with all of them.

Also added in making sure to clone the branch being checked (it was still cloning the latest release) and checking that a request is successful after install.

**Review by alahiff — COMMENTED** [review]
`realpath` doesn't seem to exist on MacOS by default:
```
./localregistry.sh: line 53: realpath: command not found
```
While I think it's possible to install `realpath` on MacOS, I think it's best to minimize the number of dependencies to keep things simple for users.

**Comment by alahiff** [comment]
The help text refers to `local_registry.sh` but the name of the file is currently `localregistry.sh`.

**Comment by kzscisoft** [comment]
> `realpath` doesn't seem to exist on MacOS by default:
> 
> ```
> ./localregistry.sh: line 53: realpath: command not found
> ```
> 
> While I think it's possible to install `realpath` on MacOS, I think it's best to minimize the number of dependencies to keep things simple for users.

Damn, I think it doesn't work on the CI without it

**Comment by kzscisoft** [comment]
@alahiff I found a work around and fixed the typo

**Review by alahiff — APPROVED** [review]
Fine with me now. Successfully tested use of the install directory and port.

**Comment by richardreeve** [comment]
I was trying to test this, but I don't know how to install this branch on macOS. When I try I get:
```
bleaberry[~/Downloads] /bin/bash -c ~/Downloads/localregistry.sh -b kzscisoft/port-flag
Installing to '/Users/richardr/.fair/registry'
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
(23) Failed writing body
```
I presume that's just because I don't know what I'm doing though?

**Comment by richardreeve** [comment]
I tried replacing the grep call with sed as I suggested in #115, and it now installs, and I can start two registries on port 8000 and 8001, but I don't know if they are actually the same registry or not, since they offer me tokens in the same place? Do I need to install two separate registries to different install directories?

**Review by richardreeve — CHANGES_REQUESTED** [review]
I'm not exactly sure what the `grep -Po` statement was supposed to be doing, but this may have fixed the problem I had with downloading this branch to test it anyway?

**Comment by kzscisoft** [comment]
> I tried replacing the grep call with sed as I suggested in #115, and it now installs, and I can start two registries on port 8000 and 8001, but I don't know if they are actually the same registry or not, since they offer me tokens in the same place? Do I need to install two separate registries to different install directories?

Are you using the `-d` flag to specify an alternative directory for install?

**Comment by alahiff** [comment]
> @richardreeve @alahiff as this addresses the grep issue as well am I ok to put an auto close statement for #115 ?

Fine with me, thanks!

**Comment by kzscisoft** [comment]
Fixes #115

**Review by richardreeve — APPROVED** [review]
Thanks @kzscisoft - I had failed to have two installation directories. Is there somewhere obvious to add a bit of documentation on how to connect to a different port / to start up two registries on the same machine? Otherwise looks good to me now.

**Comment by alahiff** [comment]
>  Is there somewhere obvious to add a bit of documentation on how to connect to a different port / to start up two registries on the same machine? 

We should add something about both this and the ability to specify tags/branches etc in the documentation here:

https://fairdatapipeline.github.io/docs/local_registry/

**Comment by richardreeve** [comment]
Okay, if that's the right place to put the docs, then we can presumably merge this and raise an issue in that repo for the docs?

**Comment by richardreeve** [comment]
@alahiff Shall we merge this then, and then sort out the docs next?

**Pull request merged**
