### PR TITLE
Add issues to data products in prov report and remove redundant function

### PR DESCRIPTION
**Pull request by nathan-cummings-ukaea**
Does this look reasonable? I'm having trouble with Zulip right now by the way so I won't see any messages there for the moment.

### CODE REVIEW

**Comment by agbeltran** [comment]
@antony-wilson @nathan-cummings-ukaea we could still use this branch to replace ```prov:type``` with ```rdf:type```

**Comment by nathan-cummings-ukaea** [comment]
If you want to replace prov:type with rdf:type before we merge this go ahead. After that I think it can be merged.

**Comment by nathan-cummings-ukaea** [comment]
The one 'code smell' is a bit annoying and a perfectly legitimate complaint, however I think arbitrarily breaking up this function to make the warning go away doesn't massively help.

The fact is, manually changing the dot object in this way was a pain and required a weird, hacky solution.

**Comment by agbeltran** [comment]
we decided to address the ```rdf:type``` replacement in another PR

**Review by agbeltran — APPROVED** [review]

**Pull request merged**
