### PR TITLE
Add windows batch scripts

### PR DESCRIPTION
**Pull request by RyanJField**
Translated static/localregistry.sh to static/localregistry.bat

And scripts/start_fair_registry.sh to start_fair_registry_window.bat

To allow the registry to be run locally (natively) on windows.

Note: start_fair_registry_window.bat will spawn a new window to run the python server because windows does not have an equivalent of nohup

### CODE REVIEW

**Comment by alahiff** [comment]
Ideally it would be good if another Windows user could confirm this works for them. Apart from that I'm happy for this to be merged.

**Comment by richardreeve** [comment]
Are there instructions somewhere I could follow? I don't know anything about Windows, I have a clean Windows VM sitting idle here...

**Comment by RyanJField** [comment]
> Are there instructions somewhere I could follow (some time this afternoon)? I don't know anything about Windows, but I have a clean Windows VM sitting idle here...

Hi Richard, I'll draft some instructions today and let you know when they're ready.

Ryan

**Comment by RyanJField** [comment]
> > Are there instructions somewhere I could follow (some time this afternoon)? I don't know anything about Windows, but I have a clean Windows VM sitting idle here...
> 
> Hi Richard, I'll draft some instructions today and let you know when they're ready.
> 
> Ryan

Instructions (these will be edited and added to the github.io site after testing.

Windows:

Prerequisites:
For the registry scripts to run the following programs need to be installed and added to the system or user PATH:
Chocolatey (https://chocolatey.org/)
Python 3 (https://community.chocolatey.org/packages/python/3.9.7)
CURL (https://community.chocolatey.org/packages/curl)
	(Both Python 3 and CURL can be installed using Chocolatey)
	
Steps to run the registry locally on windows:
run:  static/localregistry.bat (this will be available from the https://data.scrc.uk site once the pull request is approved.

run: scripts/start_fair_registry_windows.bat to start the registry.
	This script should spawn the server in a new window, with instructions on how to stop the server when needed.
	
You can manually specify the port using scripts/start_fair_registry_windows.bat -p <port>
The default port is 8000

**Comment by richardreeve** [comment]
Great, thanks. A couple of things - I really have never used Windows! - how do I add Chocolatey (and Python 3 and curl) to the user / system path? Is it obvious / automatic when I do the install? And how do I install the registry itself? And do I open some kind of terminal to run the start and stop commands?

**Comment by richardreeve** [comment]
Okay, the puzzlingly unhelpful Chocolatey installation instructions seem to have added things to my path by default now I've figured them out, so I have Chocolately, python and curl installed. However, the installation instructions for the registry are:
```
/bin/bash -c "$(curl -fsSL https://data.scrc.uk/static/localregistry.sh)"
```
which I understand on mac/linux, but I don't know how to do the equivalent on Windows?

**Comment by richardreeve** [comment]
Oh, sorry - do you mean that `static/localregistry.bat` installs the registry? I thought it ran the registry, but I now see that there is a `scripts/start_fair_registry_windows.bat` too.

**Comment by RyanJField** [comment]
> Oh, sorry - do you mean that `static/localregistry.bat` installs the registry? I thought it ran the registry, but I now see that there is a `scripts/start_fair_registry_windows.bat` too.

Yes `static/localregistry.bat` installs the registry and `scripts/start_fair_registry_windows.bat` runs the registry.

**Comment by richardreeve** [comment]
Great, thanks!

So... minor addition to the installation notes - you also need to use choco to install git. Also, do you need to run PowerShell, and run it as admin to do this? I couldn't work out how to do it either with the Command Prompt (no instructions for installing choco) or without admin rights, but I didn't try very hard as I didn't know what I was doing!

But that all works for me now. Thanks so much! Sorry for asking stupid questions. Windows is a mystery to me.

**Comment by richardreeve** [comment]
PS I could run the registry not as admin incidentally...

**Comment by richardreeve** [comment]
PPS I'm happy for it to be merged!

**Comment by RyanJField** [comment]
> Great, thanks!
> 
> So... minor addition to the installation notes - you also need to use choco to install git. Also, do you need to run PowerShell, and run it as admin to do this? I couldn't work out how to do it either with the Command Prompt (no instructions for installing choco) or without admin rights, but I didn't try very hard as I didn't know what I was doing!
> 
> But that all works for me now. Thanks so much! Sorry for asking stupid questions. Windows is a mystery to me.

Ah yes, I assumed GIT would be installed, I will make it clear it is a prerequisite, Chocolatey needs an admin powershell to install: https://chocolatey.org/install but you also need to run the code to ensure Get-ExecutionPolicy is not Restricted so it can be difficult to get it installed.

If the admin PowerShell for Chocolatey is an issue (thinking of safe haven etc) there are workarounds to this (installing git, python, curl and using user paths) however due to a windows limitation the user may have to log off an log back on (or restart) at one point to refresh the environmental variables.

The registry should not need admin rights to run as it does not modify any system files or paths as it uses user environmental variables rather than system environmental variables.

**Comment by richardreeve** [comment]
Those installation notes for Chocolatey start with "First, ensure that you are using an administrative shell - you can also install as a non-admin, check out Non-Administrative Installation." and `adminstrative shell` links to https://www.howtogeek.com/194041/how-to-open-the-command-prompt-as-administrator-in-windows-8.1/ which is about the Command Prompt, which wasn't very helpful, but I got there in the end. Anyway, please do merge away. Thanks again!

**Review by richardreeve — APPROVED** [review]

**Pull request merged**
